### ISSUE TITLE
Can this be compiled on windows?

### ISSUE THREAD

**Issue by lsysyem** [rgoldade/AdaptiveViscositySolver#1]
Can this be compiled on windows?

**Comment by rgoldade** [comment]
I haven't tried it so I can't say for certain. It _should_ but there are subtle differences between Visual Studio and GCC/Clang that might cause errors. There is a section on compiling in Windows in Houdini's HDK documentation (https://www.sidefx.com/docs/hdk/_h_d_k__intro__compiling.html#HDK_Intro_Compiling_Windows).

**Comment by lsysyem** [comment]
> I haven't tried it so I can't say for certain. It _should_ but there are subtle differences between Visual Studio and GCC/Clang that might cause errors. There is a section on compiling in Windows in Houdini's HDK documentation (https://www.sidefx.com/docs/hdk/_h_d_k__intro__compiling.html#HDK_Intro_Compiling_Windows).
