### ISSUE TITLE
Does Houdini Apprentice work with this repo?

### ISSUE THREAD

**Issue by songyang-dev** [rgoldade/AdaptiveViscositySolver#6]
Hello, I'm looking to replicate your study for my grad course. I can't purchase Houdini. But there is a free, student version of Houdini called Houdini Apprentice. I wonder if your code works there.

**Comment by rgoldade** [comment]
Hi, I haven't verified it but since Houdini Apprentice has the full VFX feature set, it should work. I will try it and get back to you.

**Comment by rgoldade** [comment]
Confirmed. Works with Apprentice.
